name: nature360

description: 360 Nature Viewer Demo

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  provider: ^6.1.2

  panorama_viewer: ^2.0.6

  flutter_animate: ^4.5.2

  google_fonts: ^6.3.1

flutter:

  uses-material-design: true

  assets:

    - assets/images/

    - assets/images/places/